### ISSUE TITLE
Auto hide side bar stopped working with Obsidian 1.2.8

### ISSUE THREAD

**Issue by OmniNaut** [skelato1/obsidian-auto-hide#13]
Since upgrading to Obsidian 1.2.8 (insider) the auto hide side bar option stopped working, If I click in a note, the side bar does not close anymore.
I'm not sure if this happened because upgrading to 1.2.8 or because I was upgrading the installation version to 1.2.7 (from1.1.5)

Obsidian v1.2.8 
Installation version 1.2.7
Windows 11 22H2

**Comment by skelato1** [comment]
I couldn't test with Obsidian 1.2.8 because I'm not an insider of Obsidian. But when I updated the installer version to 1.2.7, this issue occurred.

I fixed this issue and updated the release. Thank you for the information.
