### ISSUE TITLE
the search function of tag isn't displayed

### ISSUE THREAD

**Issue by math-feng** [skelato1/obsidian-auto-hide#17]
Clicking on a tag in the yaml section does not properly display the tag's search function on the left side.
![Obsidian_24_02_08_22](https://github.com/skelato1/obsidian-auto-hide/assets/78469397/a8fe988e-383c-4b73-a8a9-a371e679ad2a)
Automatically hides the left sidebar as shown above

**Comment by skelato1** [comment]
fixed it!
