### ISSUE TITLE
Linking Issues

### ISSUE THREAD

**Issue by math-feng** [skelato1/obsidian-auto-hide#18]
When clicking on the link generated by the Strange New Worlds plugin, the right sidebar still does not display properly. Same problem as #17 ！
![Obsidian_24_02_09_28](https://github.com/skelato1/obsidian-auto-hide/assets/78469397/ae827085-e7f7-49f3-88c1-92af4e9f5bd8)

**Comment by skelato1** [comment]
fixed it!
