### ISSUE TITLE
Feature request: Side pane locking

### ISSUE THREAD

**Issue by BoxThatBeat** [skelato1/obsidian-auto-hide#2]
First of all, I love this plugin! Thanks for making this, it really improves workflow.

A feature I'd love to see would be having lock icons at the top right of both side panes and when that is clicked, the pane becomes locked in place so it won't close when you click on a note!

Let me know if you like the idea or if you'd like me to take a crack at it 😄

**Comment by skelato1** [comment]
Hi Aaron!

Thank you for your feature request!
I totally agree with your thoughts and think we need such a feature.
But I don't have much time for development. Therefore, it will take some time until this feature is completed.🙁
However, I can also merge your pull request if you wish!

**Comment by skelato1** [comment]
I added this feature on version 0.4.0! But it may occur bugs with custom CSS themes.

**Comment by BoxThatBeat** [comment]
@skelato1 Just tried it out and it looks so good and works perfectly! Thanks for adding that! Nice job 👍
