### ISSUE TITLE
Doesnt work for right pane with 0.16

### ISSUE THREAD

**Issue by danieltomasz** [skelato1/obsidian-auto-hide#3]
I cannot open the right sidebar on 0.16, the autohider automatically hides it (also the new buttons for sidebar doesnt work)
I dont expect it  to be solved before 0.16 will be publicly released, but might will be useful for users add this info to README page   until this will be solved

If this is useful, https://github.com/NomarCub/obsidian-hide-sidebars-on-window-resize doesn't have this problem

**Comment by skelato1** [comment]
Fixed in 0.4.1. Please comment if it still happens!
