### ISSUE TITLE
Switching Workspaces stop functionality

### ISSUE THREAD

**Issue by pdelre** [skelato1/obsidian-auto-hide#4]
When I switch Workspaces the functionality stops. What I can see is that the newly added "Pin" button also doesn't render, which feels like the plugin isn't "reloaded" (I'm not familiar with Obsidian events) when the workspace is loaded. No errors appear in the Dev Tools Console logs.

**Comment by skelato1** [comment]
Fixed in 0.4.2!
thank you for information.
