### ISSUE TITLE
Pin state indistinguishable

### ISSUE THREAD

**Issue by BoxThatBeat** [skelato1/obsidian-auto-hide#6]
Since v1 of Obsidian came out, on all themes I have tried including the default, there is no visual difference between the pin logo when active or non-active. I believe this had been the case before?

**Comment by skelato1** [comment]
Before v1, Minimal Theme has this problem. ("pin" icon and "filled-pin" icon are same svg)
Maybe obsidian v1 merged Minimal Theme. so that problem is occur any themes. 
I think we should add new icons to plugin.

**Comment by skelato1** [comment]
Added new icons to the plugin in 0.4.3, and probably it works.
