### ISSUE TITLE
Click the path in  tab title bar can't open file explore

### ISSUE THREAD

**Issue by ribber** [skelato1/obsidian-auto-hide#8]
There is a new feature in 1.0. We can open it in setting -> Appearance -> Show tab title bar

When click the path，Obsidian will display fold in file explore.

But when this plugin is enable, the file explore will close soon

![Image 1](https://user-images.githubusercontent.com/5986011/195966506-a7bd1a8b-810e-482b-b9f6-4f586710cfbb.png)
.

**Comment by suliveevil** [comment]
And it conflicts with Shimmering-focus's Breadcrumbs.

**Comment by skelato1** [comment]
Fix in 0.4.3. Thanks for the information!
